[package]
name = "core_utils"
authors = ["Mark-S-Hill"]
description = "Core Utilities"
version = "0.0.1"
edition = "2018"

[dependencies]
chrono = "0.4"
jwalk = "0.6.0"

[[bin]]
name = "count_files"
path = "src/count_files.rs"